version: '3'
services:
  db:
    image: mysql:8.0.21
    ports:
      - '3333:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password0#'
      MYSQL_DATABASE: 'proto'