CREATE TABLE `user` (
	`user_id` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_name` VARCHAR (20) CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` NOT NULL,
	`email_address` VARCHAR (255) CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` NOT NULL,
	`tel_number` VARCHAR (16) CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`user_id`)
);

CREATE TABLE `notification` (
	`id` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`uid` INT (10) UNSIGNED NOT NULL,
	`json` json,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX `uid` (`uid`),
	PRIMARY KEY (`id`)
) AUTO_INCREMENT = 1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;